import { Outfit } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '../lib/redux/provider';
import { Toaster } from 'react-hot-toast';
import '../lib/fontawesome.ts';
import ClientLayout from './clientLayout'; // wrap the client logic

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata = {
  title: 'Mech-Moto : Revolution in Auto Care',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${outfit.variable} font-sans`}>
      <body className="antialiased">
        <ClientLayout>
          <Toaster />
          <ReduxProvider>{children}</ReduxProvider>
        </ClientLayout>
      </body>
    </html>
  );
}
