import "./globals.css";
import { ReduxProvider } from "../lib/redux/provider";
import { Toaster } from "react-hot-toast";
import "../lib/fontawesome.ts";
import { Outfit, Roboto, DM_Sans, Poppins } from "next/font/google";
import ClientLayoutWrapper from "@/components/layout/ClientLayoutWrapper";

// Load fonts
const outfit = Outfit({
	subsets: ["latin"],
	variable: "--font-outfit",
	weight: ["300", "400", "500", "600", "700"],
});

const roboto = Roboto({
	subsets: ["latin"],
	weight: ["400", "500", "700"],
	variable: "--font-roboto",
	display: "swap",
});

const dmSans = DM_Sans({
	subsets: ["latin"],
	variable: "--font-dm-sans",
	weight: ["400", "500", "700"],
	display: "swap",
});

const poppins = Poppins({
	subsets: ["latin"],
	variable: "--font-poppins",
	weight: ["300", "400", "500", "600", "700"],
	display: "swap",
});

export const metadata = {
	title: "Mech-Moto : Revolution in Auto Care",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html
			lang="en"
			className={`${outfit.variable} ${roboto.variable} ${dmSans.variable} ${poppins.variable} font-sans`}
		>
			<body className="antialiased">
				<ReduxProvider>
					<ClientLayoutWrapper>
						{children}
						<Toaster
							position="top-right"
							reverseOrder={false}
						/>
					</ClientLayoutWrapper>
				</ReduxProvider>
			</body>
		</html>
	);
}
